name: "Build and deploy tomato"
on:
  push:
    branches:
      - "main"
env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    name: "build"
    runs-on: ubuntu-20.04
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-java@v2"
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: "compile and run tests"
        run: "mvn install"

      - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push the Docker image"
        run: |
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}

      - name: nais SBOM attestation Action
        uses: nais/attestation@v0.0.1-alpha-1
        with:
          image: ${{ env.IMAGE }}
          key: ${{ secrets.COSIGN_KEY }}
          key_pwd: ${{ secrets.COSIGN_KEY_PWD }}
          docker_user: ${{ github.actor }}
          docker_pwd: ${{ secrets.GITHUB_TOKEN }}
