name: "Build and deploy tomato"
on:
  push:
    branches:
      - "main"
env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  KEY: gcpkms://projects/plattformsikkerhet-dev-496e/locations/europe-north1/keyRings/cosign/cryptoKeys/cosign-test/versions/1
jobs:
  build:
    name: "build"
    runs-on: ubuntu-20.04
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-java@v2"
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: "compile and run tests"
        run: "mvn install"

      - name: "Login to GitHub Docker Registry"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push the Docker image"
        run: |
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}

      - uses: anchore/sbom-action@v0
        with:
          image: {{ env.IMAGE }}
          registry-username: {{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
